// MACHINE GENERATED BY 'go generate' COMMAND; DO NOT EDIT

package x86

import "errors"

type Syscall struct {
	Num   int
	Name  string
	Entry string
	Args  []Argument
}

type Argument struct {
	RefCount int
	Sig      string
	Context  Context
}

type Context int

const (
	CTX_NONE Context = iota
	CTX_FD
)

var syscalls = map[int]Syscall{
	0: Syscall{
		Num: 0,
		Name: "restart_syscall",
		Entry: "sys_restart_syscall",
		Args: []Argument{

		},
	},
	1: Syscall{
		Num: 1,
		Name: "exit",
		Entry: "sys_exit",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int error_code",
				Context: 0,
			},

		},
	},
	2: Syscall{
		Num: 2,
		Name: "fork",
		Entry: "sys_fork",
		Args: []Argument{

		},
	},
	3: Syscall{
		Num: 3,
		Name: "read",
		Entry: "sys_read",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned int fd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "char __user *buf",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "size_t count",
				Context: 0,
			},

		},
	},
	4: Syscall{
		Num: 4,
		Name: "write",
		Entry: "sys_write",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned int fd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user *buf",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "size_t count",
				Context: 0,
			},

		},
	},
	5: Syscall{
		Num: 5,
		Name: "open",
		Entry: "sys_open",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *filename",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int flags",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "umode_t mode",
				Context: 0,
			},

		},
	},
	6: Syscall{
		Num: 6,
		Name: "close",
		Entry: "sys_close",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned int fd",
				Context: 0,
			},

		},
	},
	7: Syscall{
		Num: 7,
		Name: "waitpid",
		Entry: "sys_waitpid",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "pid_t pid",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "int __user *stat_addr",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int options",
				Context: 0,
			},

		},
	},
	8: Syscall{
		Num: 8,
		Name: "creat",
		Entry: "sys_creat",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *pathname",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "umode_t mode",
				Context: 0,
			},

		},
	},
	9: Syscall{
		Num: 9,
		Name: "link",
		Entry: "sys_link",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *oldname",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user *newname",
				Context: 0,
			},

		},
	},
	10: Syscall{
		Num: 10,
		Name: "unlink",
		Entry: "sys_unlink",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *pathname",
				Context: 0,
			},

		},
	},
	11: Syscall{
		Num: 11,
		Name: "execve",
		Entry: "sys_execve",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *filename",
				Context: 0,
			},
			{
				RefCount: 2,
				Sig: "const char __user *const __user *argv",
				Context: 0,
			},
			{
				RefCount: 2,
				Sig: "const char __user *const __user *envp",
				Context: 0,
			},

		},
	},
	12: Syscall{
		Num: 12,
		Name: "chdir",
		Entry: "sys_chdir",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *filename",
				Context: 0,
			},

		},
	},
	13: Syscall{
		Num: 13,
		Name: "time",
		Entry: "sys_time",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "time_t __user *tloc",
				Context: 0,
			},

		},
	},
	14: Syscall{
		Num: 14,
		Name: "mknod",
		Entry: "sys_mknod",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *filename",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "umode_t mode",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned dev",
				Context: 0,
			},

		},
	},
	15: Syscall{
		Num: 15,
		Name: "chmod",
		Entry: "sys_chmod",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *filename",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "umode_t mode",
				Context: 0,
			},

		},
	},
	16: Syscall{
		Num: 16,
		Name: "lchown",
		Entry: "sys_lchown16",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *filename",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "old_uid_t user",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "old_gid_t group",
				Context: 0,
			},

		},
	},
	18: Syscall{
		Num: 18,
		Name: "oldstat",
		Entry: "sys_stat",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *filename",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct __old_kernel_stat __user *statbuf",
				Context: 0,
			},

		},
	},
	19: Syscall{
		Num: 19,
		Name: "lseek",
		Entry: "sys_lseek",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned int fd",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "off_t offset",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned int whence",
				Context: 0,
			},

		},
	},
	20: Syscall{
		Num: 20,
		Name: "getpid",
		Entry: "sys_getpid",
		Args: []Argument{

		},
	},
	21: Syscall{
		Num: 21,
		Name: "mount",
		Entry: "sys_mount",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "char __user *dev_name",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "char __user *dir_name",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "char __user *type",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long flags",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "void __user *data",
				Context: 0,
			},

		},
	},
	22: Syscall{
		Num: 22,
		Name: "umount",
		Entry: "sys_oldumount",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "char __user *name",
				Context: 0,
			},

		},
	},
	23: Syscall{
		Num: 23,
		Name: "setuid",
		Entry: "sys_setuid16",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "old_uid_t uid",
				Context: 0,
			},

		},
	},
	24: Syscall{
		Num: 24,
		Name: "getuid",
		Entry: "sys_getuid16",
		Args: []Argument{

		},
	},
	25: Syscall{
		Num: 25,
		Name: "stime",
		Entry: "sys_stime",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "time_t __user *tptr",
				Context: 0,
			},

		},
	},
	26: Syscall{
		Num: 26,
		Name: "ptrace",
		Entry: "sys_ptrace",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "long request",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "long pid",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long addr",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long data",
				Context: 0,
			},

		},
	},
	27: Syscall{
		Num: 27,
		Name: "alarm",
		Entry: "sys_alarm",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned int seconds",
				Context: 0,
			},

		},
	},
	28: Syscall{
		Num: 28,
		Name: "oldfstat",
		Entry: "sys_fstat",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned int fd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct __old_kernel_stat __user *statbuf",
				Context: 0,
			},

		},
	},
	29: Syscall{
		Num: 29,
		Name: "pause",
		Entry: "sys_pause",
		Args: []Argument{

		},
	},
	30: Syscall{
		Num: 30,
		Name: "utime",
		Entry: "sys_utime",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "char __user *filename",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct utimbuf __user *times",
				Context: 0,
			},

		},
	},
	33: Syscall{
		Num: 33,
		Name: "access",
		Entry: "sys_access",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *filename",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int mode",
				Context: 0,
			},

		},
	},
	34: Syscall{
		Num: 34,
		Name: "nice",
		Entry: "sys_nice",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int increment",
				Context: 0,
			},

		},
	},
	36: Syscall{
		Num: 36,
		Name: "sync",
		Entry: "sys_sync",
		Args: []Argument{

		},
	},
	37: Syscall{
		Num: 37,
		Name: "kill",
		Entry: "sys_kill",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int pid",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int sig",
				Context: 0,
			},

		},
	},
	38: Syscall{
		Num: 38,
		Name: "rename",
		Entry: "sys_rename",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *oldname",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user *newname",
				Context: 0,
			},

		},
	},
	39: Syscall{
		Num: 39,
		Name: "mkdir",
		Entry: "sys_mkdir",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *pathname",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "umode_t mode",
				Context: 0,
			},

		},
	},
	40: Syscall{
		Num: 40,
		Name: "rmdir",
		Entry: "sys_rmdir",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *pathname",
				Context: 0,
			},

		},
	},
	41: Syscall{
		Num: 41,
		Name: "dup",
		Entry: "sys_dup",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned int fildes",
				Context: 0,
			},

		},
	},
	42: Syscall{
		Num: 42,
		Name: "pipe",
		Entry: "sys_pipe",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "int __user *fildes",
				Context: 0,
			},

		},
	},
	43: Syscall{
		Num: 43,
		Name: "times",
		Entry: "sys_times",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "struct tms __user *tbuf",
				Context: 0,
			},

		},
	},
	45: Syscall{
		Num: 45,
		Name: "brk",
		Entry: "sys_brk",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned long brk",
				Context: 0,
			},

		},
	},
	46: Syscall{
		Num: 46,
		Name: "setgid",
		Entry: "sys_setgid16",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "old_gid_t gid",
				Context: 0,
			},

		},
	},
	47: Syscall{
		Num: 47,
		Name: "getgid",
		Entry: "sys_getgid16",
		Args: []Argument{

		},
	},
	48: Syscall{
		Num: 48,
		Name: "signal",
		Entry: "sys_signal",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int sig",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "__sighandler_t handler",
				Context: 0,
			},

		},
	},
	49: Syscall{
		Num: 49,
		Name: "geteuid",
		Entry: "sys_geteuid16",
		Args: []Argument{

		},
	},
	50: Syscall{
		Num: 50,
		Name: "getegid",
		Entry: "sys_getegid16",
		Args: []Argument{

		},
	},
	51: Syscall{
		Num: 51,
		Name: "acct",
		Entry: "sys_acct",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *name",
				Context: 0,
			},

		},
	},
	52: Syscall{
		Num: 52,
		Name: "umount2",
		Entry: "sys_umount",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "char __user *name",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int flags",
				Context: 0,
			},

		},
	},
	54: Syscall{
		Num: 54,
		Name: "ioctl",
		Entry: "sys_ioctl",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned int fd",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned int cmd",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long arg",
				Context: 0,
			},

		},
	},
	55: Syscall{
		Num: 55,
		Name: "fcntl",
		Entry: "sys_fcntl",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned int fd",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned int cmd",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long arg",
				Context: 0,
			},

		},
	},
	57: Syscall{
		Num: 57,
		Name: "setpgid",
		Entry: "sys_setpgid",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "pid_t pid",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "pid_t pgid",
				Context: 0,
			},

		},
	},
	59: Syscall{
		Num: 59,
		Name: "oldolduname",
		Entry: "sys_olduname",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "struct oldold_utsname __user *",
				Context: 0,
			},

		},
	},
	60: Syscall{
		Num: 60,
		Name: "umask",
		Entry: "sys_umask",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int mask",
				Context: 0,
			},

		},
	},
	61: Syscall{
		Num: 61,
		Name: "chroot",
		Entry: "sys_chroot",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *filename",
				Context: 0,
			},

		},
	},
	62: Syscall{
		Num: 62,
		Name: "ustat",
		Entry: "sys_ustat",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned dev",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct ustat __user *ubuf",
				Context: 0,
			},

		},
	},
	63: Syscall{
		Num: 63,
		Name: "dup2",
		Entry: "sys_dup2",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned int oldfd",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned int newfd",
				Context: 0,
			},

		},
	},
	64: Syscall{
		Num: 64,
		Name: "getppid",
		Entry: "sys_getppid",
		Args: []Argument{

		},
	},
	65: Syscall{
		Num: 65,
		Name: "getpgrp",
		Entry: "sys_getpgrp",
		Args: []Argument{

		},
	},
	66: Syscall{
		Num: 66,
		Name: "setsid",
		Entry: "sys_setsid",
		Args: []Argument{

		},
	},
	67: Syscall{
		Num: 67,
		Name: "sigaction",
		Entry: "sys_sigaction",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const struct old_sigaction __user *",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct old_sigaction __user *",
				Context: 0,
			},

		},
	},
	68: Syscall{
		Num: 68,
		Name: "sgetmask",
		Entry: "sys_sgetmask",
		Args: []Argument{

		},
	},
	69: Syscall{
		Num: 69,
		Name: "ssetmask",
		Entry: "sys_ssetmask",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int newmask",
				Context: 0,
			},

		},
	},
	70: Syscall{
		Num: 70,
		Name: "setreuid",
		Entry: "sys_setreuid16",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "old_uid_t ruid",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "old_uid_t euid",
				Context: 0,
			},

		},
	},
	71: Syscall{
		Num: 71,
		Name: "setregid",
		Entry: "sys_setregid16",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "old_gid_t rgid",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "old_gid_t egid",
				Context: 0,
			},

		},
	},
	72: Syscall{
		Num: 72,
		Name: "sigsuspend",
		Entry: "sys_sigsuspend",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int unused1",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int unused2",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "old_sigset_t mask",
				Context: 0,
			},

		},
	},
	73: Syscall{
		Num: 73,
		Name: "sigpending",
		Entry: "sys_sigpending",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "old_sigset_t __user *set",
				Context: 0,
			},

		},
	},
	74: Syscall{
		Num: 74,
		Name: "sethostname",
		Entry: "sys_sethostname",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "char __user *name",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int len",
				Context: 0,
			},

		},
	},
	75: Syscall{
		Num: 75,
		Name: "setrlimit",
		Entry: "sys_setrlimit",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned int resource",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct rlimit __user *rlim",
				Context: 0,
			},

		},
	},
	76: Syscall{
		Num: 76,
		Name: "getrlimit",
		Entry: "sys_old_getrlimit",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned int resource",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct rlimit __user *rlim",
				Context: 0,
			},

		},
	},
	77: Syscall{
		Num: 77,
		Name: "getrusage",
		Entry: "sys_getrusage",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int who",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct rusage __user *ru",
				Context: 0,
			},

		},
	},
	78: Syscall{
		Num: 78,
		Name: "gettimeofday",
		Entry: "sys_gettimeofday",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "struct timeval __user *tv",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct timezone __user *tz",
				Context: 0,
			},

		},
	},
	79: Syscall{
		Num: 79,
		Name: "settimeofday",
		Entry: "sys_settimeofday",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "struct timeval __user *tv",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct timezone __user *tz",
				Context: 0,
			},

		},
	},
	80: Syscall{
		Num: 80,
		Name: "getgroups",
		Entry: "sys_getgroups16",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int gidsetsize",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "old_gid_t __user *grouplist",
				Context: 0,
			},

		},
	},
	81: Syscall{
		Num: 81,
		Name: "setgroups",
		Entry: "sys_setgroups16",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int gidsetsize",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "old_gid_t __user *grouplist",
				Context: 0,
			},

		},
	},
	82: Syscall{
		Num: 82,
		Name: "select",
		Entry: "sys_old_select",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "struct sel_arg_struct __user *arg",
				Context: 0,
			},

		},
	},
	83: Syscall{
		Num: 83,
		Name: "symlink",
		Entry: "sys_symlink",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *old",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user *new",
				Context: 0,
			},

		},
	},
	84: Syscall{
		Num: 84,
		Name: "oldlstat",
		Entry: "sys_lstat",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *filename",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct __old_kernel_stat __user *statbuf",
				Context: 0,
			},

		},
	},
	85: Syscall{
		Num: 85,
		Name: "readlink",
		Entry: "sys_readlink",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *path",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "char __user *buf",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int bufsiz",
				Context: 0,
			},

		},
	},
	86: Syscall{
		Num: 86,
		Name: "uselib",
		Entry: "sys_uselib",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *library",
				Context: 0,
			},

		},
	},
	87: Syscall{
		Num: 87,
		Name: "swapon",
		Entry: "sys_swapon",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *specialfile",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int swap_flags",
				Context: 0,
			},

		},
	},
	88: Syscall{
		Num: 88,
		Name: "reboot",
		Entry: "sys_reboot",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int magic1",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int magic2",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned int cmd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "void __user *arg",
				Context: 0,
			},

		},
	},
	89: Syscall{
		Num: 89,
		Name: "readdir",
		Entry: "sys_old_readdir",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned int",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct old_linux_dirent __user *",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned int",
				Context: 0,
			},

		},
	},
	90: Syscall{
		Num: 90,
		Name: "mmap",
		Entry: "sys_old_mmap",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "struct mmap_arg_struct __user *arg",
				Context: 0,
			},

		},
	},
	91: Syscall{
		Num: 91,
		Name: "munmap",
		Entry: "sys_munmap",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned long addr",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "size_t len",
				Context: 0,
			},

		},
	},
	92: Syscall{
		Num: 92,
		Name: "truncate",
		Entry: "sys_truncate",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *path",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "long length",
				Context: 0,
			},

		},
	},
	93: Syscall{
		Num: 93,
		Name: "ftruncate",
		Entry: "sys_ftruncate",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned int fd",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long length",
				Context: 0,
			},

		},
	},
	94: Syscall{
		Num: 94,
		Name: "fchmod",
		Entry: "sys_fchmod",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned int fd",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "umode_t mode",
				Context: 0,
			},

		},
	},
	95: Syscall{
		Num: 95,
		Name: "fchown",
		Entry: "sys_fchown16",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned int fd",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "old_uid_t user",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "old_gid_t group",
				Context: 0,
			},

		},
	},
	96: Syscall{
		Num: 96,
		Name: "getpriority",
		Entry: "sys_getpriority",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int which",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int who",
				Context: 0,
			},

		},
	},
	97: Syscall{
		Num: 97,
		Name: "setpriority",
		Entry: "sys_setpriority",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int which",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int who",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int niceval",
				Context: 0,
			},

		},
	},
	99: Syscall{
		Num: 99,
		Name: "statfs",
		Entry: "sys_statfs",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user * path",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct statfs __user *buf",
				Context: 0,
			},

		},
	},
	100: Syscall{
		Num: 100,
		Name: "fstatfs",
		Entry: "sys_fstatfs",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned int fd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct statfs __user *buf",
				Context: 0,
			},

		},
	},
	101: Syscall{
		Num: 101,
		Name: "ioperm",
		Entry: "sys_ioperm",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned long",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int",
				Context: 0,
			},

		},
	},
	102: Syscall{
		Num: 102,
		Name: "socketcall",
		Entry: "sys_socketcall",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int call",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "unsigned long __user *args",
				Context: 0,
			},

		},
	},
	103: Syscall{
		Num: 103,
		Name: "syslog",
		Entry: "sys_syslog",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int type",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "char __user *buf",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int len",
				Context: 0,
			},

		},
	},
	104: Syscall{
		Num: 104,
		Name: "setitimer",
		Entry: "sys_setitimer",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int which",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct itimerval __user *value",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct itimerval __user *ovalue",
				Context: 0,
			},

		},
	},
	105: Syscall{
		Num: 105,
		Name: "getitimer",
		Entry: "sys_getitimer",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int which",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct itimerval __user *value",
				Context: 0,
			},

		},
	},
	106: Syscall{
		Num: 106,
		Name: "stat",
		Entry: "sys_newstat",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *filename",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct stat __user *statbuf",
				Context: 0,
			},

		},
	},
	107: Syscall{
		Num: 107,
		Name: "lstat",
		Entry: "sys_newlstat",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *filename",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct stat __user *statbuf",
				Context: 0,
			},

		},
	},
	108: Syscall{
		Num: 108,
		Name: "fstat",
		Entry: "sys_newfstat",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned int fd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct stat __user *statbuf",
				Context: 0,
			},

		},
	},
	109: Syscall{
		Num: 109,
		Name: "olduname",
		Entry: "sys_uname",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "struct old_utsname __user *",
				Context: 0,
			},

		},
	},
	110: Syscall{
		Num: 110,
		Name: "iopl",
		Entry: "sys_iopl",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned int",
				Context: 0,
			},

		},
	},
	111: Syscall{
		Num: 111,
		Name: "vhangup",
		Entry: "sys_vhangup",
		Args: []Argument{

		},
	},
	113: Syscall{
		Num: 113,
		Name: "vm86old",
		Entry: "sys_vm86old",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "struct vm86_struct __user *",
				Context: 0,
			},

		},
	},
	114: Syscall{
		Num: 114,
		Name: "wait4",
		Entry: "sys_wait4",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "pid_t pid",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "int __user *stat_addr",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int options",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct rusage __user *ru",
				Context: 0,
			},

		},
	},
	115: Syscall{
		Num: 115,
		Name: "swapoff",
		Entry: "sys_swapoff",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *specialfile",
				Context: 0,
			},

		},
	},
	116: Syscall{
		Num: 116,
		Name: "sysinfo",
		Entry: "sys_sysinfo",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "struct sysinfo __user *info",
				Context: 0,
			},

		},
	},
	117: Syscall{
		Num: 117,
		Name: "ipc",
		Entry: "sys_ipc",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned int call",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int first",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long second",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long third",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "void __user *ptr",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "long fifth",
				Context: 0,
			},

		},
	},
	118: Syscall{
		Num: 118,
		Name: "fsync",
		Entry: "sys_fsync",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned int fd",
				Context: 0,
			},

		},
	},
	119: Syscall{
		Num: 119,
		Name: "sigreturn",
		Entry: "sys_sigreturn",
		Args: []Argument{

		},
	},
	120: Syscall{
		Num: 120,
		Name: "clone",
		Entry: "sys_clone",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned long",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "int __user *",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "int __user *",
				Context: 0,
			},

		},
	},
	121: Syscall{
		Num: 121,
		Name: "setdomainname",
		Entry: "sys_setdomainname",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "char __user *name",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int len",
				Context: 0,
			},

		},
	},
	122: Syscall{
		Num: 122,
		Name: "uname",
		Entry: "sys_newuname",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "struct new_utsname __user *name",
				Context: 0,
			},

		},
	},
	123: Syscall{
		Num: 123,
		Name: "modify_ldt",
		Entry: "sys_modify_ldt",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "void __user *",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long",
				Context: 0,
			},

		},
	},
	124: Syscall{
		Num: 124,
		Name: "adjtimex",
		Entry: "sys_adjtimex",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "struct timex __user *txc_p",
				Context: 0,
			},

		},
	},
	125: Syscall{
		Num: 125,
		Name: "mprotect",
		Entry: "sys_mprotect",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned long start",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "size_t len",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long prot",
				Context: 0,
			},

		},
	},
	126: Syscall{
		Num: 126,
		Name: "sigprocmask",
		Entry: "sys_sigprocmask",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int how",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "old_sigset_t __user *set",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "old_sigset_t __user *oset",
				Context: 0,
			},

		},
	},
	128: Syscall{
		Num: 128,
		Name: "init_module",
		Entry: "sys_init_module",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "void __user *umod",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long len",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user *uargs",
				Context: 0,
			},

		},
	},
	129: Syscall{
		Num: 129,
		Name: "delete_module",
		Entry: "sys_delete_module",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *name_user",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned int flags",
				Context: 0,
			},

		},
	},
	131: Syscall{
		Num: 131,
		Name: "quotactl",
		Entry: "sys_quotactl",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned int cmd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user *special",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "qid_t id",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "void __user *addr",
				Context: 0,
			},

		},
	},
	132: Syscall{
		Num: 132,
		Name: "getpgid",
		Entry: "sys_getpgid",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "pid_t pid",
				Context: 0,
			},

		},
	},
	133: Syscall{
		Num: 133,
		Name: "fchdir",
		Entry: "sys_fchdir",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned int fd",
				Context: 0,
			},

		},
	},
	134: Syscall{
		Num: 134,
		Name: "bdflush",
		Entry: "sys_bdflush",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int func",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "long data",
				Context: 0,
			},

		},
	},
	135: Syscall{
		Num: 135,
		Name: "sysfs",
		Entry: "sys_sysfs",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int option",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long arg1",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long arg2",
				Context: 0,
			},

		},
	},
	136: Syscall{
		Num: 136,
		Name: "personality",
		Entry: "sys_personality",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned int personality",
				Context: 0,
			},

		},
	},
	138: Syscall{
		Num: 138,
		Name: "setfsuid",
		Entry: "sys_setfsuid16",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "old_uid_t uid",
				Context: 0,
			},

		},
	},
	139: Syscall{
		Num: 139,
		Name: "setfsgid",
		Entry: "sys_setfsgid16",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "old_gid_t gid",
				Context: 0,
			},

		},
	},
	140: Syscall{
		Num: 140,
		Name: "_llseek",
		Entry: "sys_llseek",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned int fd",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long offset_high",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long offset_low",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "loff_t __user *result",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned int whence",
				Context: 0,
			},

		},
	},
	141: Syscall{
		Num: 141,
		Name: "getdents",
		Entry: "sys_getdents",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned int fd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct linux_dirent __user *dirent",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned int count",
				Context: 0,
			},

		},
	},
	142: Syscall{
		Num: 142,
		Name: "_newselect",
		Entry: "sys_select",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int n",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "fd_set __user *inp",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "fd_set __user *outp",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "fd_set __user *exp",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct timeval __user *tvp",
				Context: 0,
			},

		},
	},
	143: Syscall{
		Num: 143,
		Name: "flock",
		Entry: "sys_flock",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned int fd",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned int cmd",
				Context: 0,
			},

		},
	},
	144: Syscall{
		Num: 144,
		Name: "msync",
		Entry: "sys_msync",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned long start",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "size_t len",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int flags",
				Context: 0,
			},

		},
	},
	145: Syscall{
		Num: 145,
		Name: "readv",
		Entry: "sys_readv",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned long fd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const struct iovec __user *vec",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long vlen",
				Context: 0,
			},

		},
	},
	146: Syscall{
		Num: 146,
		Name: "writev",
		Entry: "sys_writev",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned long fd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const struct iovec __user *vec",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long vlen",
				Context: 0,
			},

		},
	},
	147: Syscall{
		Num: 147,
		Name: "getsid",
		Entry: "sys_getsid",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "pid_t pid",
				Context: 0,
			},

		},
	},
	148: Syscall{
		Num: 148,
		Name: "fdatasync",
		Entry: "sys_fdatasync",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned int fd",
				Context: 0,
			},

		},
	},
	149: Syscall{
		Num: 149,
		Name: "_sysctl",
		Entry: "sys_sysctl",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "struct __sysctl_args __user *args",
				Context: 0,
			},

		},
	},
	150: Syscall{
		Num: 150,
		Name: "mlock",
		Entry: "sys_mlock",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned long start",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "size_t len",
				Context: 0,
			},

		},
	},
	151: Syscall{
		Num: 151,
		Name: "munlock",
		Entry: "sys_munlock",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned long start",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "size_t len",
				Context: 0,
			},

		},
	},
	152: Syscall{
		Num: 152,
		Name: "mlockall",
		Entry: "sys_mlockall",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int flags",
				Context: 0,
			},

		},
	},
	153: Syscall{
		Num: 153,
		Name: "munlockall",
		Entry: "sys_munlockall",
		Args: []Argument{

		},
	},
	154: Syscall{
		Num: 154,
		Name: "sched_setparam",
		Entry: "sys_sched_setparam",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "pid_t pid",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct sched_param __user *param",
				Context: 0,
			},

		},
	},
	155: Syscall{
		Num: 155,
		Name: "sched_getparam",
		Entry: "sys_sched_getparam",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "pid_t pid",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct sched_param __user *param",
				Context: 0,
			},

		},
	},
	156: Syscall{
		Num: 156,
		Name: "sched_setscheduler",
		Entry: "sys_sched_setscheduler",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "pid_t pid",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int policy",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct sched_param __user *param",
				Context: 0,
			},

		},
	},
	157: Syscall{
		Num: 157,
		Name: "sched_getscheduler",
		Entry: "sys_sched_getscheduler",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "pid_t pid",
				Context: 0,
			},

		},
	},
	158: Syscall{
		Num: 158,
		Name: "sched_yield",
		Entry: "sys_sched_yield",
		Args: []Argument{

		},
	},
	159: Syscall{
		Num: 159,
		Name: "sched_get_priority_max",
		Entry: "sys_sched_get_priority_max",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int policy",
				Context: 0,
			},

		},
	},
	160: Syscall{
		Num: 160,
		Name: "sched_get_priority_min",
		Entry: "sys_sched_get_priority_min",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int policy",
				Context: 0,
			},

		},
	},
	161: Syscall{
		Num: 161,
		Name: "sched_rr_get_interval",
		Entry: "sys_sched_rr_get_interval",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "pid_t pid",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct timespec __user *interval",
				Context: 0,
			},

		},
	},
	162: Syscall{
		Num: 162,
		Name: "nanosleep",
		Entry: "sys_nanosleep",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "struct timespec __user *rqtp",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct timespec __user *rmtp",
				Context: 0,
			},

		},
	},
	163: Syscall{
		Num: 163,
		Name: "mremap",
		Entry: "sys_mremap",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned long addr",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long old_len",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long new_len",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long flags",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long new_addr",
				Context: 0,
			},

		},
	},
	164: Syscall{
		Num: 164,
		Name: "setresuid",
		Entry: "sys_setresuid16",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "old_uid_t ruid",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "old_uid_t euid",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "old_uid_t suid",
				Context: 0,
			},

		},
	},
	165: Syscall{
		Num: 165,
		Name: "getresuid",
		Entry: "sys_getresuid16",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "old_uid_t __user *ruid",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "old_uid_t __user *euid",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "old_uid_t __user *suid",
				Context: 0,
			},

		},
	},
	166: Syscall{
		Num: 166,
		Name: "vm86",
		Entry: "sys_vm86",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned long",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long",
				Context: 0,
			},

		},
	},
	168: Syscall{
		Num: 168,
		Name: "poll",
		Entry: "sys_poll",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "struct pollfd __user *ufds",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned int nfds",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int timeout",
				Context: 0,
			},

		},
	},
	170: Syscall{
		Num: 170,
		Name: "setresgid",
		Entry: "sys_setresgid16",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "old_gid_t rgid",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "old_gid_t egid",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "old_gid_t sgid",
				Context: 0,
			},

		},
	},
	171: Syscall{
		Num: 171,
		Name: "getresgid",
		Entry: "sys_getresgid16",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "old_gid_t __user *rgid",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "old_gid_t __user *egid",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "old_gid_t __user *sgid",
				Context: 0,
			},

		},
	},
	172: Syscall{
		Num: 172,
		Name: "prctl",
		Entry: "sys_prctl",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int option",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long arg2",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long arg3",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long arg4",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long arg5",
				Context: 0,
			},

		},
	},
	173: Syscall{
		Num: 173,
		Name: "rt_sigreturn",
		Entry: "sys_rt_sigreturn",
		Args: []Argument{

		},
	},
	174: Syscall{
		Num: 174,
		Name: "rt_sigaction",
		Entry: "sys_rt_sigaction",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const struct sigaction __user *",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct sigaction __user *",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "size_t",
				Context: 0,
			},

		},
	},
	175: Syscall{
		Num: 175,
		Name: "rt_sigprocmask",
		Entry: "sys_rt_sigprocmask",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int how",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "sigset_t __user *set",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "sigset_t __user *oset",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "size_t sigsetsize",
				Context: 0,
			},

		},
	},
	176: Syscall{
		Num: 176,
		Name: "rt_sigpending",
		Entry: "sys_rt_sigpending",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "sigset_t __user *set",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "size_t sigsetsize",
				Context: 0,
			},

		},
	},
	177: Syscall{
		Num: 177,
		Name: "rt_sigtimedwait",
		Entry: "sys_rt_sigtimedwait",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const sigset_t __user *uthese",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "siginfo_t __user *uinfo",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const struct timespec __user *uts",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "size_t sigsetsize",
				Context: 0,
			},

		},
	},
	178: Syscall{
		Num: 178,
		Name: "rt_sigqueueinfo",
		Entry: "sys_rt_sigqueueinfo",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int pid",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int sig",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "siginfo_t __user *uinfo",
				Context: 0,
			},

		},
	},
	179: Syscall{
		Num: 179,
		Name: "rt_sigsuspend",
		Entry: "sys_rt_sigsuspend",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "sigset_t __user *unewset",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "size_t sigsetsize",
				Context: 0,
			},

		},
	},
	180: Syscall{
		Num: 180,
		Name: "pread64",
		Entry: "sys_pread64",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned int fd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "char __user *buf",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "size_t count",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "loff_t pos",
				Context: 0,
			},

		},
	},
	181: Syscall{
		Num: 181,
		Name: "pwrite64",
		Entry: "sys_pwrite64",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned int fd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user *buf",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "size_t count",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "loff_t pos",
				Context: 0,
			},

		},
	},
	182: Syscall{
		Num: 182,
		Name: "chown",
		Entry: "sys_chown16",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *filename",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "old_uid_t user",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "old_gid_t group",
				Context: 0,
			},

		},
	},
	183: Syscall{
		Num: 183,
		Name: "getcwd",
		Entry: "sys_getcwd",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "char __user *buf",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long size",
				Context: 0,
			},

		},
	},
	184: Syscall{
		Num: 184,
		Name: "capget",
		Entry: "sys_capget",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "cap_user_header_t header",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "cap_user_data_t dataptr",
				Context: 0,
			},

		},
	},
	185: Syscall{
		Num: 185,
		Name: "capset",
		Entry: "sys_capset",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "cap_user_header_t header",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "const cap_user_data_t data",
				Context: 0,
			},

		},
	},
	186: Syscall{
		Num: 186,
		Name: "sigaltstack",
		Entry: "sys_sigaltstack",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const struct sigaltstack __user *uss",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct sigaltstack __user *uoss",
				Context: 0,
			},

		},
	},
	187: Syscall{
		Num: 187,
		Name: "sendfile",
		Entry: "sys_sendfile",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int out_fd",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int in_fd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "off_t __user *offset",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "size_t count",
				Context: 0,
			},

		},
	},
	190: Syscall{
		Num: 190,
		Name: "vfork",
		Entry: "sys_vfork",
		Args: []Argument{

		},
	},
	191: Syscall{
		Num: 191,
		Name: "ugetrlimit",
		Entry: "sys_getrlimit",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned int resource",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct rlimit __user *rlim",
				Context: 0,
			},

		},
	},
	192: Syscall{
		Num: 192,
		Name: "mmap2",
		Entry: "sys_mmap_pgoff",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned long addr",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long len",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long prot",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long flags",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long fd",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long pgoff",
				Context: 0,
			},

		},
	},
	193: Syscall{
		Num: 193,
		Name: "truncate64",
		Entry: "sys_truncate64",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *path",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "loff_t length",
				Context: 0,
			},

		},
	},
	194: Syscall{
		Num: 194,
		Name: "ftruncate64",
		Entry: "sys_ftruncate64",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned int fd",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "loff_t length",
				Context: 0,
			},

		},
	},
	195: Syscall{
		Num: 195,
		Name: "stat64",
		Entry: "sys_stat64",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *filename",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct stat64 __user *statbuf",
				Context: 0,
			},

		},
	},
	196: Syscall{
		Num: 196,
		Name: "lstat64",
		Entry: "sys_lstat64",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *filename",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct stat64 __user *statbuf",
				Context: 0,
			},

		},
	},
	197: Syscall{
		Num: 197,
		Name: "fstat64",
		Entry: "sys_fstat64",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned long fd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct stat64 __user *statbuf",
				Context: 0,
			},

		},
	},
	198: Syscall{
		Num: 198,
		Name: "lchown32",
		Entry: "sys_lchown",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *filename",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "uid_t user",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "gid_t group",
				Context: 0,
			},

		},
	},
	199: Syscall{
		Num: 199,
		Name: "getuid32",
		Entry: "sys_getuid",
		Args: []Argument{

		},
	},
	200: Syscall{
		Num: 200,
		Name: "getgid32",
		Entry: "sys_getgid",
		Args: []Argument{

		},
	},
	201: Syscall{
		Num: 201,
		Name: "geteuid32",
		Entry: "sys_geteuid",
		Args: []Argument{

		},
	},
	202: Syscall{
		Num: 202,
		Name: "getegid32",
		Entry: "sys_getegid",
		Args: []Argument{

		},
	},
	203: Syscall{
		Num: 203,
		Name: "setreuid32",
		Entry: "sys_setreuid",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "uid_t ruid",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "uid_t euid",
				Context: 0,
			},

		},
	},
	204: Syscall{
		Num: 204,
		Name: "setregid32",
		Entry: "sys_setregid",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "gid_t rgid",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "gid_t egid",
				Context: 0,
			},

		},
	},
	205: Syscall{
		Num: 205,
		Name: "getgroups32",
		Entry: "sys_getgroups",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int gidsetsize",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "gid_t __user *grouplist",
				Context: 0,
			},

		},
	},
	206: Syscall{
		Num: 206,
		Name: "setgroups32",
		Entry: "sys_setgroups",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int gidsetsize",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "gid_t __user *grouplist",
				Context: 0,
			},

		},
	},
	207: Syscall{
		Num: 207,
		Name: "fchown32",
		Entry: "sys_fchown",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned int fd",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "uid_t user",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "gid_t group",
				Context: 0,
			},

		},
	},
	208: Syscall{
		Num: 208,
		Name: "setresuid32",
		Entry: "sys_setresuid",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "uid_t ruid",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "uid_t euid",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "uid_t suid",
				Context: 0,
			},

		},
	},
	209: Syscall{
		Num: 209,
		Name: "getresuid32",
		Entry: "sys_getresuid",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "uid_t __user *ruid",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "uid_t __user *euid",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "uid_t __user *suid",
				Context: 0,
			},

		},
	},
	210: Syscall{
		Num: 210,
		Name: "setresgid32",
		Entry: "sys_setresgid",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "gid_t rgid",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "gid_t egid",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "gid_t sgid",
				Context: 0,
			},

		},
	},
	211: Syscall{
		Num: 211,
		Name: "getresgid32",
		Entry: "sys_getresgid",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "gid_t __user *rgid",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "gid_t __user *egid",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "gid_t __user *sgid",
				Context: 0,
			},

		},
	},
	212: Syscall{
		Num: 212,
		Name: "chown32",
		Entry: "sys_chown",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *filename",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "uid_t user",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "gid_t group",
				Context: 0,
			},

		},
	},
	213: Syscall{
		Num: 213,
		Name: "setuid32",
		Entry: "sys_setuid",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "uid_t uid",
				Context: 0,
			},

		},
	},
	214: Syscall{
		Num: 214,
		Name: "setgid32",
		Entry: "sys_setgid",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "gid_t gid",
				Context: 0,
			},

		},
	},
	215: Syscall{
		Num: 215,
		Name: "setfsuid32",
		Entry: "sys_setfsuid",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "uid_t uid",
				Context: 0,
			},

		},
	},
	216: Syscall{
		Num: 216,
		Name: "setfsgid32",
		Entry: "sys_setfsgid",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "gid_t gid",
				Context: 0,
			},

		},
	},
	217: Syscall{
		Num: 217,
		Name: "pivot_root",
		Entry: "sys_pivot_root",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *new_root",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user *put_old",
				Context: 0,
			},

		},
	},
	218: Syscall{
		Num: 218,
		Name: "mincore",
		Entry: "sys_mincore",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned long start",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "size_t len",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "unsigned char __user * vec",
				Context: 0,
			},

		},
	},
	219: Syscall{
		Num: 219,
		Name: "madvise",
		Entry: "sys_madvise",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned long start",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "size_t len",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int behavior",
				Context: 0,
			},

		},
	},
	220: Syscall{
		Num: 220,
		Name: "getdents64",
		Entry: "sys_getdents64",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned int fd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct linux_dirent64 __user *dirent",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned int count",
				Context: 0,
			},

		},
	},
	221: Syscall{
		Num: 221,
		Name: "fcntl64",
		Entry: "sys_fcntl64",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned int fd",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned int cmd",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long arg",
				Context: 0,
			},

		},
	},
	224: Syscall{
		Num: 224,
		Name: "gettid",
		Entry: "sys_gettid",
		Args: []Argument{

		},
	},
	225: Syscall{
		Num: 225,
		Name: "readahead",
		Entry: "sys_readahead",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int fd",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "loff_t offset",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "size_t count",
				Context: 0,
			},

		},
	},
	226: Syscall{
		Num: 226,
		Name: "setxattr",
		Entry: "sys_setxattr",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *path",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user *name",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const void __user *value",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "size_t size",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int flags",
				Context: 0,
			},

		},
	},
	227: Syscall{
		Num: 227,
		Name: "lsetxattr",
		Entry: "sys_lsetxattr",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *path",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user *name",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const void __user *value",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "size_t size",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int flags",
				Context: 0,
			},

		},
	},
	228: Syscall{
		Num: 228,
		Name: "fsetxattr",
		Entry: "sys_fsetxattr",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int fd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user *name",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const void __user *value",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "size_t size",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int flags",
				Context: 0,
			},

		},
	},
	229: Syscall{
		Num: 229,
		Name: "getxattr",
		Entry: "sys_getxattr",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *path",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user *name",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "void __user *value",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "size_t size",
				Context: 0,
			},

		},
	},
	230: Syscall{
		Num: 230,
		Name: "lgetxattr",
		Entry: "sys_lgetxattr",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *path",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user *name",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "void __user *value",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "size_t size",
				Context: 0,
			},

		},
	},
	231: Syscall{
		Num: 231,
		Name: "fgetxattr",
		Entry: "sys_fgetxattr",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int fd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user *name",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "void __user *value",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "size_t size",
				Context: 0,
			},

		},
	},
	232: Syscall{
		Num: 232,
		Name: "listxattr",
		Entry: "sys_listxattr",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *path",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "char __user *list",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "size_t size",
				Context: 0,
			},

		},
	},
	233: Syscall{
		Num: 233,
		Name: "llistxattr",
		Entry: "sys_llistxattr",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *path",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "char __user *list",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "size_t size",
				Context: 0,
			},

		},
	},
	234: Syscall{
		Num: 234,
		Name: "flistxattr",
		Entry: "sys_flistxattr",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int fd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "char __user *list",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "size_t size",
				Context: 0,
			},

		},
	},
	235: Syscall{
		Num: 235,
		Name: "removexattr",
		Entry: "sys_removexattr",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *path",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user *name",
				Context: 0,
			},

		},
	},
	236: Syscall{
		Num: 236,
		Name: "lremovexattr",
		Entry: "sys_lremovexattr",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *path",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user *name",
				Context: 0,
			},

		},
	},
	237: Syscall{
		Num: 237,
		Name: "fremovexattr",
		Entry: "sys_fremovexattr",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int fd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user *name",
				Context: 0,
			},

		},
	},
	238: Syscall{
		Num: 238,
		Name: "tkill",
		Entry: "sys_tkill",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int pid",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int sig",
				Context: 0,
			},

		},
	},
	239: Syscall{
		Num: 239,
		Name: "sendfile64",
		Entry: "sys_sendfile64",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int out_fd",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int in_fd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "loff_t __user *offset",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "size_t count",
				Context: 0,
			},

		},
	},
	240: Syscall{
		Num: 240,
		Name: "futex",
		Entry: "sys_futex",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "u32 __user *uaddr",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int op",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "u32 val",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct timespec __user *utime",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "u32 __user *uaddr2",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "u32 val3",
				Context: 0,
			},

		},
	},
	241: Syscall{
		Num: 241,
		Name: "sched_setaffinity",
		Entry: "sys_sched_setaffinity",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "pid_t pid",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned int len",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "unsigned long __user *user_mask_ptr",
				Context: 0,
			},

		},
	},
	242: Syscall{
		Num: 242,
		Name: "sched_getaffinity",
		Entry: "sys_sched_getaffinity",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "pid_t pid",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned int len",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "unsigned long __user *user_mask_ptr",
				Context: 0,
			},

		},
	},
	243: Syscall{
		Num: 243,
		Name: "set_thread_area",
		Entry: "sys_set_thread_area",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "struct user_desc __user *",
				Context: 0,
			},

		},
	},
	244: Syscall{
		Num: 244,
		Name: "get_thread_area",
		Entry: "sys_get_thread_area",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "struct user_desc __user *",
				Context: 0,
			},

		},
	},
	245: Syscall{
		Num: 245,
		Name: "io_setup",
		Entry: "sys_io_setup",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned nr_reqs",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "aio_context_t __user *ctx",
				Context: 0,
			},

		},
	},
	246: Syscall{
		Num: 246,
		Name: "io_destroy",
		Entry: "sys_io_destroy",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "aio_context_t ctx",
				Context: 0,
			},

		},
	},
	247: Syscall{
		Num: 247,
		Name: "io_getevents",
		Entry: "sys_io_getevents",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "aio_context_t ctx_id",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "long min_nr",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "long nr",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct io_event __user *events",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct timespec __user *timeout",
				Context: 0,
			},

		},
	},
	248: Syscall{
		Num: 248,
		Name: "io_submit",
		Entry: "sys_io_submit",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "aio_context_t",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "long",
				Context: 0,
			},
			{
				RefCount: 2,
				Sig: "struct iocb __user * __user *",
				Context: 0,
			},

		},
	},
	249: Syscall{
		Num: 249,
		Name: "io_cancel",
		Entry: "sys_io_cancel",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "aio_context_t ctx_id",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct iocb __user *iocb",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct io_event __user *result",
				Context: 0,
			},

		},
	},
	250: Syscall{
		Num: 250,
		Name: "fadvise64",
		Entry: "sys_fadvise64",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int fd",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "loff_t offset",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "size_t len",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int advice",
				Context: 0,
			},

		},
	},
	252: Syscall{
		Num: 252,
		Name: "exit_group",
		Entry: "sys_exit_group",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int error_code",
				Context: 0,
			},

		},
	},
	253: Syscall{
		Num: 253,
		Name: "lookup_dcookie",
		Entry: "sys_lookup_dcookie",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "u64 cookie64",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "char __user *buf",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "size_t len",
				Context: 0,
			},

		},
	},
	254: Syscall{
		Num: 254,
		Name: "epoll_create",
		Entry: "sys_epoll_create",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int size",
				Context: 0,
			},

		},
	},
	255: Syscall{
		Num: 255,
		Name: "epoll_ctl",
		Entry: "sys_epoll_ctl",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int epfd",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int op",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int fd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct epoll_event __user *event",
				Context: 0,
			},

		},
	},
	256: Syscall{
		Num: 256,
		Name: "epoll_wait",
		Entry: "sys_epoll_wait",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int epfd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct epoll_event __user *events",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int maxevents",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int timeout",
				Context: 0,
			},

		},
	},
	257: Syscall{
		Num: 257,
		Name: "remap_file_pages",
		Entry: "sys_remap_file_pages",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned long start",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long size",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long prot",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long pgoff",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long flags",
				Context: 0,
			},

		},
	},
	258: Syscall{
		Num: 258,
		Name: "set_tid_address",
		Entry: "sys_set_tid_address",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "int __user *tidptr",
				Context: 0,
			},

		},
	},
	259: Syscall{
		Num: 259,
		Name: "timer_create",
		Entry: "sys_timer_create",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "clockid_t which_clock",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct sigevent __user *timer_event_spec",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "timer_t __user * created_timer_id",
				Context: 0,
			},

		},
	},
	260: Syscall{
		Num: 260,
		Name: "timer_settime",
		Entry: "sys_timer_settime",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "timer_t timer_id",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int flags",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const struct itimerspec __user *new_setting",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct itimerspec __user *old_setting",
				Context: 0,
			},

		},
	},
	261: Syscall{
		Num: 261,
		Name: "timer_gettime",
		Entry: "sys_timer_gettime",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "timer_t timer_id",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct itimerspec __user *setting",
				Context: 0,
			},

		},
	},
	262: Syscall{
		Num: 262,
		Name: "timer_getoverrun",
		Entry: "sys_timer_getoverrun",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "timer_t timer_id",
				Context: 0,
			},

		},
	},
	263: Syscall{
		Num: 263,
		Name: "timer_delete",
		Entry: "sys_timer_delete",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "timer_t timer_id",
				Context: 0,
			},

		},
	},
	264: Syscall{
		Num: 264,
		Name: "clock_settime",
		Entry: "sys_clock_settime",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "clockid_t which_clock",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const struct timespec __user *tp",
				Context: 0,
			},

		},
	},
	265: Syscall{
		Num: 265,
		Name: "clock_gettime",
		Entry: "sys_clock_gettime",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "clockid_t which_clock",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct timespec __user *tp",
				Context: 0,
			},

		},
	},
	266: Syscall{
		Num: 266,
		Name: "clock_getres",
		Entry: "sys_clock_getres",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "clockid_t which_clock",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct timespec __user *tp",
				Context: 0,
			},

		},
	},
	267: Syscall{
		Num: 267,
		Name: "clock_nanosleep",
		Entry: "sys_clock_nanosleep",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "clockid_t which_clock",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int flags",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const struct timespec __user *rqtp",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct timespec __user *rmtp",
				Context: 0,
			},

		},
	},
	268: Syscall{
		Num: 268,
		Name: "statfs64",
		Entry: "sys_statfs64",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *path",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "size_t sz",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct statfs64 __user *buf",
				Context: 0,
			},

		},
	},
	269: Syscall{
		Num: 269,
		Name: "fstatfs64",
		Entry: "sys_fstatfs64",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned int fd",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "size_t sz",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct statfs64 __user *buf",
				Context: 0,
			},

		},
	},
	270: Syscall{
		Num: 270,
		Name: "tgkill",
		Entry: "sys_tgkill",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int tgid",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int pid",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int sig",
				Context: 0,
			},

		},
	},
	271: Syscall{
		Num: 271,
		Name: "utimes",
		Entry: "sys_utimes",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "char __user *filename",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct timeval __user *utimes",
				Context: 0,
			},

		},
	},
	272: Syscall{
		Num: 272,
		Name: "fadvise64_64",
		Entry: "sys_fadvise64_64",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int fd",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "loff_t offset",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "loff_t len",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int advice",
				Context: 0,
			},

		},
	},
	274: Syscall{
		Num: 274,
		Name: "mbind",
		Entry: "sys_mbind",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned long start",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long len",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long mode",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const unsigned long __user *nmask",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long maxnode",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned flags",
				Context: 0,
			},

		},
	},
	275: Syscall{
		Num: 275,
		Name: "get_mempolicy",
		Entry: "sys_get_mempolicy",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "int __user *policy",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "unsigned long __user *nmask",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long maxnode",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long addr",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long flags",
				Context: 0,
			},

		},
	},
	276: Syscall{
		Num: 276,
		Name: "set_mempolicy",
		Entry: "sys_set_mempolicy",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int mode",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const unsigned long __user *nmask",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long maxnode",
				Context: 0,
			},

		},
	},
	277: Syscall{
		Num: 277,
		Name: "mq_open",
		Entry: "sys_mq_open",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *name",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int oflag",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "umode_t mode",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct mq_attr __user *attr",
				Context: 0,
			},

		},
	},
	278: Syscall{
		Num: 278,
		Name: "mq_unlink",
		Entry: "sys_mq_unlink",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *name",
				Context: 0,
			},

		},
	},
	279: Syscall{
		Num: 279,
		Name: "mq_timedsend",
		Entry: "sys_mq_timedsend",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "mqd_t mqdes",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user *msg_ptr",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "size_t msg_len",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned int msg_prio",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const struct timespec __user *abs_timeout",
				Context: 0,
			},

		},
	},
	280: Syscall{
		Num: 280,
		Name: "mq_timedreceive",
		Entry: "sys_mq_timedreceive",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "mqd_t mqdes",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "char __user *msg_ptr",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "size_t msg_len",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "unsigned int __user *msg_prio",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const struct timespec __user *abs_timeout",
				Context: 0,
			},

		},
	},
	281: Syscall{
		Num: 281,
		Name: "mq_notify",
		Entry: "sys_mq_notify",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "mqd_t mqdes",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const struct sigevent __user *notification",
				Context: 0,
			},

		},
	},
	282: Syscall{
		Num: 282,
		Name: "mq_getsetattr",
		Entry: "sys_mq_getsetattr",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "mqd_t mqdes",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const struct mq_attr __user *mqstat",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct mq_attr __user *omqstat",
				Context: 0,
			},

		},
	},
	283: Syscall{
		Num: 283,
		Name: "kexec_load",
		Entry: "sys_kexec_load",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned long entry",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long nr_segments",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct kexec_segment __user *segments",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long flags",
				Context: 0,
			},

		},
	},
	284: Syscall{
		Num: 284,
		Name: "waitid",
		Entry: "sys_waitid",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int which",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "pid_t pid",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct siginfo __user *infop",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int options",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct rusage __user *ru",
				Context: 0,
			},

		},
	},
	286: Syscall{
		Num: 286,
		Name: "add_key",
		Entry: "sys_add_key",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *_type",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user *_description",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const void __user *_payload",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "size_t plen",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "key_serial_t destringid",
				Context: 0,
			},

		},
	},
	287: Syscall{
		Num: 287,
		Name: "request_key",
		Entry: "sys_request_key",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *_type",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user *_description",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user *_callout_info",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "key_serial_t destringid",
				Context: 0,
			},

		},
	},
	288: Syscall{
		Num: 288,
		Name: "keyctl",
		Entry: "sys_keyctl",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int cmd",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long arg2",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long arg3",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long arg4",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long arg5",
				Context: 0,
			},

		},
	},
	289: Syscall{
		Num: 289,
		Name: "ioprio_set",
		Entry: "sys_ioprio_set",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int which",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int who",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int ioprio",
				Context: 0,
			},

		},
	},
	290: Syscall{
		Num: 290,
		Name: "ioprio_get",
		Entry: "sys_ioprio_get",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int which",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int who",
				Context: 0,
			},

		},
	},
	291: Syscall{
		Num: 291,
		Name: "inotify_init",
		Entry: "sys_inotify_init",
		Args: []Argument{

		},
	},
	292: Syscall{
		Num: 292,
		Name: "inotify_add_watch",
		Entry: "sys_inotify_add_watch",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int fd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user *path",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "u32 mask",
				Context: 0,
			},

		},
	},
	293: Syscall{
		Num: 293,
		Name: "inotify_rm_watch",
		Entry: "sys_inotify_rm_watch",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int fd",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "__s32 wd",
				Context: 0,
			},

		},
	},
	294: Syscall{
		Num: 294,
		Name: "migrate_pages",
		Entry: "sys_migrate_pages",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "pid_t pid",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long maxnode",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const unsigned long __user *from",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const unsigned long __user *to",
				Context: 0,
			},

		},
	},
	295: Syscall{
		Num: 295,
		Name: "openat",
		Entry: "sys_openat",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int dfd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user *filename",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int flags",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "umode_t mode",
				Context: 0,
			},

		},
	},
	296: Syscall{
		Num: 296,
		Name: "mkdirat",
		Entry: "sys_mkdirat",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int dfd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user * pathname",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "umode_t mode",
				Context: 0,
			},

		},
	},
	297: Syscall{
		Num: 297,
		Name: "mknodat",
		Entry: "sys_mknodat",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int dfd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user * filename",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "umode_t mode",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned dev",
				Context: 0,
			},

		},
	},
	298: Syscall{
		Num: 298,
		Name: "fchownat",
		Entry: "sys_fchownat",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int dfd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user *filename",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "uid_t user",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "gid_t group",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int flag",
				Context: 0,
			},

		},
	},
	299: Syscall{
		Num: 299,
		Name: "futimesat",
		Entry: "sys_futimesat",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int dfd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user *filename",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct timeval __user *utimes",
				Context: 0,
			},

		},
	},
	300: Syscall{
		Num: 300,
		Name: "fstatat64",
		Entry: "sys_fstatat64",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int dfd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user *filename",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct stat64 __user *statbuf",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int flag",
				Context: 0,
			},

		},
	},
	301: Syscall{
		Num: 301,
		Name: "unlinkat",
		Entry: "sys_unlinkat",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int dfd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user * pathname",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int flag",
				Context: 0,
			},

		},
	},
	302: Syscall{
		Num: 302,
		Name: "renameat",
		Entry: "sys_renameat",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int olddfd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user * oldname",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int newdfd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user * newname",
				Context: 0,
			},

		},
	},
	303: Syscall{
		Num: 303,
		Name: "linkat",
		Entry: "sys_linkat",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int olddfd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user *oldname",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int newdfd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user *newname",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int flags",
				Context: 0,
			},

		},
	},
	304: Syscall{
		Num: 304,
		Name: "symlinkat",
		Entry: "sys_symlinkat",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user * oldname",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int newdfd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user * newname",
				Context: 0,
			},

		},
	},
	305: Syscall{
		Num: 305,
		Name: "readlinkat",
		Entry: "sys_readlinkat",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int dfd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user *path",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "char __user *buf",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int bufsiz",
				Context: 0,
			},

		},
	},
	306: Syscall{
		Num: 306,
		Name: "fchmodat",
		Entry: "sys_fchmodat",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int dfd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user * filename",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "umode_t mode",
				Context: 0,
			},

		},
	},
	307: Syscall{
		Num: 307,
		Name: "faccessat",
		Entry: "sys_faccessat",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int dfd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user *filename",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int mode",
				Context: 0,
			},

		},
	},
	308: Syscall{
		Num: 308,
		Name: "pselect6",
		Entry: "sys_pselect6",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int n",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "fd_set __user *inp",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "fd_set __user *outp",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "fd_set __user *exp",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct timespec __user *tsp",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "void __user *sig",
				Context: 0,
			},

		},
	},
	309: Syscall{
		Num: 309,
		Name: "ppoll",
		Entry: "sys_ppoll",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "struct pollfd __user *ufds",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned int nfds",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct timespec __user *tsp",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const sigset_t __user *sigmask",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "size_t sigsetsize",
				Context: 0,
			},

		},
	},
	310: Syscall{
		Num: 310,
		Name: "unshare",
		Entry: "sys_unshare",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned long unshare_flags",
				Context: 0,
			},

		},
	},
	311: Syscall{
		Num: 311,
		Name: "set_robust_list",
		Entry: "sys_set_robust_list",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "struct robust_list_head __user *head",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "size_t len",
				Context: 0,
			},

		},
	},
	312: Syscall{
		Num: 312,
		Name: "get_robust_list",
		Entry: "sys_get_robust_list",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int pid",
				Context: 0,
			},
			{
				RefCount: 2,
				Sig: "struct robust_list_head __user * __user *head_ptr",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "size_t __user *len_ptr",
				Context: 0,
			},

		},
	},
	313: Syscall{
		Num: 313,
		Name: "splice",
		Entry: "sys_splice",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int fd_in",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "loff_t __user *off_in",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int fd_out",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "loff_t __user *off_out",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "size_t len",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned int flags",
				Context: 0,
			},

		},
	},
	314: Syscall{
		Num: 314,
		Name: "sync_file_range",
		Entry: "sys_sync_file_range",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int fd",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "loff_t offset",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "loff_t nbytes",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned int flags",
				Context: 0,
			},

		},
	},
	315: Syscall{
		Num: 315,
		Name: "tee",
		Entry: "sys_tee",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int fdin",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int fdout",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "size_t len",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned int flags",
				Context: 0,
			},

		},
	},
	316: Syscall{
		Num: 316,
		Name: "vmsplice",
		Entry: "sys_vmsplice",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int fd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const struct iovec __user *iov",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long nr_segs",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned int flags",
				Context: 0,
			},

		},
	},
	317: Syscall{
		Num: 317,
		Name: "move_pages",
		Entry: "sys_move_pages",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "pid_t pid",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long nr_pages",
				Context: 0,
			},
			{
				RefCount: 2,
				Sig: "const void __user * __user *pages",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const int __user *nodes",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "int __user *status",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int flags",
				Context: 0,
			},

		},
	},
	318: Syscall{
		Num: 318,
		Name: "getcpu",
		Entry: "sys_getcpu",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "unsigned __user *cpu",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "unsigned __user *node",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct getcpu_cache __user *cache",
				Context: 0,
			},

		},
	},
	319: Syscall{
		Num: 319,
		Name: "epoll_pwait",
		Entry: "sys_epoll_pwait",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int epfd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct epoll_event __user *events",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int maxevents",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int timeout",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const sigset_t __user *sigmask",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "size_t sigsetsize",
				Context: 0,
			},

		},
	},
	320: Syscall{
		Num: 320,
		Name: "utimensat",
		Entry: "sys_utimensat",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int dfd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user *filename",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct timespec __user *utimes",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int flags",
				Context: 0,
			},

		},
	},
	321: Syscall{
		Num: 321,
		Name: "signalfd",
		Entry: "sys_signalfd",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int ufd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "sigset_t __user *user_mask",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "size_t sizemask",
				Context: 0,
			},

		},
	},
	322: Syscall{
		Num: 322,
		Name: "timerfd_create",
		Entry: "sys_timerfd_create",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int clockid",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int flags",
				Context: 0,
			},

		},
	},
	323: Syscall{
		Num: 323,
		Name: "eventfd",
		Entry: "sys_eventfd",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned int count",
				Context: 0,
			},

		},
	},
	324: Syscall{
		Num: 324,
		Name: "fallocate",
		Entry: "sys_fallocate",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int fd",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int mode",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "loff_t offset",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "loff_t len",
				Context: 0,
			},

		},
	},
	325: Syscall{
		Num: 325,
		Name: "timerfd_settime",
		Entry: "sys_timerfd_settime",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int ufd",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int flags",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const struct itimerspec __user *utmr",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct itimerspec __user *otmr",
				Context: 0,
			},

		},
	},
	326: Syscall{
		Num: 326,
		Name: "timerfd_gettime",
		Entry: "sys_timerfd_gettime",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int ufd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct itimerspec __user *otmr",
				Context: 0,
			},

		},
	},
	327: Syscall{
		Num: 327,
		Name: "signalfd4",
		Entry: "sys_signalfd4",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int ufd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "sigset_t __user *user_mask",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "size_t sizemask",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int flags",
				Context: 0,
			},

		},
	},
	328: Syscall{
		Num: 328,
		Name: "eventfd2",
		Entry: "sys_eventfd2",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned int count",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int flags",
				Context: 0,
			},

		},
	},
	329: Syscall{
		Num: 329,
		Name: "epoll_create1",
		Entry: "sys_epoll_create1",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int flags",
				Context: 0,
			},

		},
	},
	330: Syscall{
		Num: 330,
		Name: "dup3",
		Entry: "sys_dup3",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned int oldfd",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned int newfd",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int flags",
				Context: 0,
			},

		},
	},
	331: Syscall{
		Num: 331,
		Name: "pipe2",
		Entry: "sys_pipe2",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "int __user *fildes",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int flags",
				Context: 0,
			},

		},
	},
	332: Syscall{
		Num: 332,
		Name: "inotify_init1",
		Entry: "sys_inotify_init1",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int flags",
				Context: 0,
			},

		},
	},
	333: Syscall{
		Num: 333,
		Name: "preadv",
		Entry: "sys_preadv",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned long fd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const struct iovec __user *vec",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long vlen",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long pos_l",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long pos_h",
				Context: 0,
			},

		},
	},
	334: Syscall{
		Num: 334,
		Name: "pwritev",
		Entry: "sys_pwritev",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned long fd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const struct iovec __user *vec",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long vlen",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long pos_l",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long pos_h",
				Context: 0,
			},

		},
	},
	335: Syscall{
		Num: 335,
		Name: "rt_tgsigqueueinfo",
		Entry: "sys_rt_tgsigqueueinfo",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "pid_t tgid",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "pid_t pid",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int sig",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "siginfo_t __user *uinfo",
				Context: 0,
			},

		},
	},
	336: Syscall{
		Num: 336,
		Name: "perf_event_open",
		Entry: "sys_perf_event_open",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "struct perf_event_attr __user *attr_uptr",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "pid_t pid",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int cpu",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int group_fd",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long flags",
				Context: 0,
			},

		},
	},
	337: Syscall{
		Num: 337,
		Name: "recvmmsg",
		Entry: "sys_recvmmsg",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int fd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct mmsghdr __user *msg",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned int vlen",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned flags",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct timespec __user *timeout",
				Context: 0,
			},

		},
	},
	338: Syscall{
		Num: 338,
		Name: "fanotify_init",
		Entry: "sys_fanotify_init",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned int flags",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned int event_f_flags",
				Context: 0,
			},

		},
	},
	339: Syscall{
		Num: 339,
		Name: "fanotify_mark",
		Entry: "sys_fanotify_mark",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int fanotify_fd",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned int flags",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "u64 mask",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int fd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user *pathname",
				Context: 0,
			},

		},
	},
	340: Syscall{
		Num: 340,
		Name: "prlimit64",
		Entry: "sys_prlimit64",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "pid_t pid",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned int resource",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const struct rlimit64 __user *new_rlim",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct rlimit64 __user *old_rlim",
				Context: 0,
			},

		},
	},
	341: Syscall{
		Num: 341,
		Name: "name_to_handle_at",
		Entry: "sys_name_to_handle_at",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int dfd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user *name",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct file_handle __user *handle",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "int __user *mnt_id",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int flag",
				Context: 0,
			},

		},
	},
	342: Syscall{
		Num: 342,
		Name: "open_by_handle_at",
		Entry: "sys_open_by_handle_at",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int mountdirfd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct file_handle __user *handle",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int flags",
				Context: 0,
			},

		},
	},
	343: Syscall{
		Num: 343,
		Name: "clock_adjtime",
		Entry: "sys_clock_adjtime",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "clockid_t which_clock",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct timex __user *tx",
				Context: 0,
			},

		},
	},
	344: Syscall{
		Num: 344,
		Name: "syncfs",
		Entry: "sys_syncfs",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int fd",
				Context: 0,
			},

		},
	},
	345: Syscall{
		Num: 345,
		Name: "sendmmsg",
		Entry: "sys_sendmmsg",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int fd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct mmsghdr __user *msg",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned int vlen",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned flags",
				Context: 0,
			},

		},
	},
	346: Syscall{
		Num: 346,
		Name: "setns",
		Entry: "sys_setns",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int fd",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int nstype",
				Context: 0,
			},

		},
	},
	347: Syscall{
		Num: 347,
		Name: "process_vm_readv",
		Entry: "sys_process_vm_readv",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "pid_t pid",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const struct iovec __user *lvec",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long liovcnt",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const struct iovec __user *rvec",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long riovcnt",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long flags",
				Context: 0,
			},

		},
	},
	348: Syscall{
		Num: 348,
		Name: "process_vm_writev",
		Entry: "sys_process_vm_writev",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "pid_t pid",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const struct iovec __user *lvec",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long liovcnt",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const struct iovec __user *rvec",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long riovcnt",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long flags",
				Context: 0,
			},

		},
	},
	349: Syscall{
		Num: 349,
		Name: "kcmp",
		Entry: "sys_kcmp",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "pid_t pid1",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "pid_t pid2",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int type",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long idx1",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned long idx2",
				Context: 0,
			},

		},
	},
	350: Syscall{
		Num: 350,
		Name: "finit_module",
		Entry: "sys_finit_module",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int fd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user *uargs",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int flags",
				Context: 0,
			},

		},
	},
	351: Syscall{
		Num: 351,
		Name: "sched_setattr",
		Entry: "sys_sched_setattr",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "pid_t pid",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct sched_attr __user *attr",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned int flags",
				Context: 0,
			},

		},
	},
	352: Syscall{
		Num: 352,
		Name: "sched_getattr",
		Entry: "sys_sched_getattr",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "pid_t pid",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "struct sched_attr __user *attr",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned int size",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned int flags",
				Context: 0,
			},

		},
	},
	353: Syscall{
		Num: 353,
		Name: "renameat2",
		Entry: "sys_renameat2",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int olddfd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user *oldname",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int newdfd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user *newname",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned int flags",
				Context: 0,
			},

		},
	},
	354: Syscall{
		Num: 354,
		Name: "seccomp",
		Entry: "sys_seccomp",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "unsigned int op",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned int flags",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user *uargs",
				Context: 0,
			},

		},
	},
	355: Syscall{
		Num: 355,
		Name: "getrandom",
		Entry: "sys_getrandom",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "char __user *buf",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "size_t count",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned int flags",
				Context: 0,
			},

		},
	},
	356: Syscall{
		Num: 356,
		Name: "memfd_create",
		Entry: "sys_memfd_create",
		Args: []Argument{
			{
				RefCount: 1,
				Sig: "const char __user *uname_ptr",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned int flags",
				Context: 0,
			},

		},
	},
	357: Syscall{
		Num: 357,
		Name: "bpf",
		Entry: "sys_bpf",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int cmd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "union bpf_attr *attr",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "unsigned int size",
				Context: 0,
			},

		},
	},
	358: Syscall{
		Num: 358,
		Name: "execveat",
		Entry: "sys_execveat",
		Args: []Argument{
			{
				RefCount: 0,
				Sig: "int dfd",
				Context: 0,
			},
			{
				RefCount: 1,
				Sig: "const char __user *filename",
				Context: 0,
			},
			{
				RefCount: 2,
				Sig: "const char __user *const __user *argv",
				Context: 0,
			},
			{
				RefCount: 2,
				Sig: "const char __user *const __user *envp",
				Context: 0,
			},
			{
				RefCount: 0,
				Sig: "int flags",
				Context: 0,
			},

		},
	},
}

func GetSyscall(n int) (Syscall, error) {
	sc, ok := syscalls[n]
	if !ok {
		return Syscall{}, errors.New("unknown syscall")
	}
	return sc, nil
}

func GetSyscallByEntry(entry string) (Syscall, error) {
	for _, sc := range syscalls {
		if sc.Entry == entry {
			return sc, nil
		}
	}
	return Syscall{}, errors.New("unknown syscall")
}
