// +build ignore

package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"text/template"
)

var (
	arch     = flag.String("arch", "amd64", "architecture corresponding to the context file")
	filename = flag.String("output", "", "output file name (standard output if omitted)")
)

type Syscall struct {
	Num   int
	Name  string
	Entry string
	Args  []Argument
}

type Argument struct {
	RefCount int
	Sig      string
	Context  Context
}

type Context int

const (
	CTX_NONE Context = iota
	CTX_FD
)

func (ctx *Context) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("context should be a string, got %s", data)
	}
	switch s {
	case "FD":
		*ctx = CTX_FD
	default:
		*ctx = CTX_NONE
	}
	return nil
}

type SyscallinfoPackage struct {
	Arch     string
	Syscalls []Syscall
}

func main() {
	flag.Usage = usage
	flag.Parse()
	if len(flag.Args()) != 1 {
		usage()
	}
	ctxfile := flag.Arg(0)

	ctxdata, err := ioutil.ReadFile(ctxfile)
	if err != nil {
		log.Fatalln(err)
	}

	sipkg := SyscallinfoPackage{Arch: *arch}
	if err := json.Unmarshal(ctxdata, &sipkg.Syscalls); err != nil {
		log.Fatalln(err)
	}

	var buf bytes.Buffer
	t := template.Must(template.New("src").Parse(srcTemplate))
	if err := t.Execute(&buf, sipkg); err != nil {
		log.Fatalln(err)
	}
	if *filename != "" {
		err = ioutil.WriteFile(*filename, buf.Bytes(), 0644)
	} else {
		_, err = os.Stdout.Write(buf.Bytes())
	}
	if err != nil {
		log.Fatalln(err)
	}
}

func usage() {
	fmt.Fprintf(os.Stderr, "usage: mksyscallinfo_linux [flags] arch ctxfile\n")
	flag.PrintDefaults()
	os.Exit(2)
}

const srcTemplate = `// MACHINE GENERATED BY 'go generate' COMMAND; DO NOT EDIT

package {{.Arch}}

import "errors"

type Syscall struct {
	Num   int
	Name  string
	Entry string
	Args  []Argument
}

type Argument struct {
	RefCount int
	Sig      string
	Context  Context
}

type Context int

const (
	CTX_NONE Context = iota
	CTX_FD
)

var syscalls = map[int]Syscall{
{{range .Syscalls}}	{{.Num}}: Syscall{
		Num: {{.Num}},
		Name: "{{.Name}}",
		Entry: "{{.Entry}}",
		Args: []Argument{
{{range .Args}}			{
				RefCount: {{.RefCount}},
				Sig: "{{.Sig}}",
				Context: {{.Context}},
			},
{{end}}
		},
	},
{{end}}}

func GetSyscall(n int) (Syscall, error) {
	sc, ok := syscalls[n]
	if !ok {
		return Syscall{}, errors.New("unknown syscall")
	}
	return sc, nil
}

func GetSyscallByEntry(entry string) (Syscall, error) {
	for _, sc := range syscalls {
		if sc.Entry == entry {
			return sc, nil
		}
	}
	return Syscall{}, errors.New("unknown syscall")
}
`
